[book]
title = "UNIT PWM Module Documentation"
authors = ["UNIT Electronics"]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "theme"
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
additional-css = ["theme/custom.css"]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0
